version: '3.7'
services:
  backend:
    build:
      context: /backend
      dockerfile: Dockerfile
    image: elicot/setlist-backend-image:latest
    ports:
      - "8888:8888"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  frontend:
    build:
      context: /frontend
      dockerfile: Dockerfile
    image: elicot/setlist-frontend-image:latest
    ports:
      - "3000:3000"
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - REACT_APP_BACKEND_URL=backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure