name: Deploy and Update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doppler CLI
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh
          doppler --version

      - name: Retrieve secrets from Doppler
        run: doppler secrets download --no-file --format env
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          DOPPLER_PROJECT: setlist-generator

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Container Registry
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker images
        run: |
          docker buildx build --tag elicot/setlist-frontend-image:latest --push frontend
          docker buildx build --tag elicot/setlist-backend-image:latest --push backend

      - name: SSH into remote server and update Docker Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd /home/Github/setListGenerator
            git fetch
            git pull
            DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }} docker stack deploy -c docker-stack.yml setlist-generator
        env:
          SECRET_KEY: $SECRET_KEY
          MONGO_URI: $MONGO_URI
          REACT_APP_BACKEND_URL: $REACT_APP_BACKEND_URL