- name: Install Doppler CLI
  run: |
    curl -L https://cli.doppler.com/install | sh
    sudo mv /usr/local/bin/doppler /usr/bin/
  env:
    DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

- name: Retrieve secrets from Doppler
  run: doppler secrets download --no-file --format env
  env:
    DOPPLER_PROJECT: setlist-generator

- name: Deploy to Docker Swarm

  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build backend Docker image
          run: docker build -t my-backend-image ./backend

        - name: Build frontend Docker image
          run: docker build -t my-frontend-image ./frontend

        - name: Login to Docker Hub
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        - name: Push backend Docker image
          run: docker push my-backend-image

        - name: Push frontend Docker image
          run: docker push my-frontend-image

        - name: SSH into remote server and update Docker Stack
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.REMOTE_SERVER }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.REMOTE_PORT }}
            script: |
              docker stack deploy -c docker-compose.yml setlist-generator