name: Deploy and Update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Doppler CLI
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh
          doppler --version

      - name: Retrieve secrets from Doppler
        run: doppler secrets download --no-file --format env
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          DOPPLER_PROJECT: setlist-generator
          
      # - name: Where am i?
      #   run: cd /home/runner/work/setListGenerator
        
      # - name: Build backend Docker image
      #   run: |
      #     ls -lha
      #     cd /home/runner/work/setListGenerator
      #     docker build -t my-backend-image ./backend

      # - name: Build frontend Docker image
      #   run:  |
      #     cd /home/runner/work/setListGenerator
      #     docker build -t my-frontend-image ./frontend

      - name: SSH into remote server and update Docker Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ~/home/Github/setListGenerator
            git fetch
            git pull
            docker stack deploy -c docker-compose.yml setlist-generator
